spring:
  application:
    name: lab
  datasource:
    url: jdbc:mysql://localhost:3306/lab?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: lab
    password: lab
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
