server:
  port: 8081

spring:
  application:
    name: learn-kafka
  datasource:
    url: jdbc:h2:mem:kafkadb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: false
  h2:
    console:
      enabled: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: product-metrics-group

logging:
  pattern:
    console: "%msg%n"
  level:
    root: WARN
    lab.learn.kafka: INFO
    org.apache.kafka: WARN
